insert into Clinics (ClinicName, CreatedDate) Values ('Aðýz, Diþ ve Çene Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Aðýz, Diþ ve Çene Radyolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Aile Hekimliði',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Algoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Amatem (Alkol ve Madde Baðýmlýlýðý)',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Anesteziyoloji ve Reanimasyon',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Beyin ve Sinir Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Cerrahi Onkolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Diþ Hekimliði',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Endokrinolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Enfeksiyon Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Gastroenterolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Genetik Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Göðüs Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Hematolojisi ve Onkolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Ýmmünolojisi ve Alerji Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Kalp Damar Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Kardiyolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Metabolizma Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Nefrolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Nörolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Romatolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Saðlýðý ve Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk Ürolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk ve Ergen Madde ve Alkol Baðýmlýlýðý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Çocuk ve Ergen Ruh Saðlýðý ve Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Deri ve Zührevi Hastalýklarý (Cildiye)',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Diþ Hekimliði (Genel Diþ)',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('El Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Endodonti',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Endokrinoloji ve Metabolizma Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Enfeksiyon Hastalýklarý ve Klinik Mikrobiyoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Fiziksel Týp ve Rehabilitasyon',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Gastroenteroloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Gastroenteroloji Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Geleneksel Tamamlayýcý Týp Ünitesi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Geliþimsel Pediatri',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Göz Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Hava ve Uzay Hekimliði',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Hematoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Ýç Hastalýklarý (Dahiliye)',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Ýmmünoloji ve Alerji Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Ýþ ve Meslek Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Jinekolojik Onkoloji Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Kadýn Hastalýklarý ve Doðum',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Kalp ve Damar Cerrahisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Kardiyoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Kulak Burun Boðaz Hastalýklarý',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Nefroloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Neonatoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Nöroloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Nükleer Týp',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Ortodonti',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Ortopedi ve Travmatoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Perinatoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Periodontoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Plastik, Rekonstrüktif ve Estetik Cerrahi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Protetik Diþ Tedavisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Radyasyon Onkolojisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Restoratif Diþ Tedavisi',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Romatoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Ruh Saðlýðý ve Hastalýklarý (Psikiyatri)',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Saðlýk Kurulu',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Saðlýk Kurulu ÇÖZGER (Çocuk Özel Gereksinim Raporu)',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Sigarayý Býraktýrma Kliniði',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Spor Hekimliði',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Sualtý Hekimliði ve Hiperbarik Týp',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Týbbi Ekoloji ve Hidroklimatoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Týbbi Genetik',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Týbbi Onkoloji',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Uyku Polikliniði',GETDATE());
insert into Clinics (ClinicName, CreatedDate) Values ('Üroloji',GETDATE());